# Generated by Django 4.1 on 2024-10-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='年级')),
            ],
            options={
                'verbose_name': '年级',
                'db_table': 'grade',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='班级')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.grade')),
            ],
            options={
                'verbose_name': '班级',
                'db_table': 'group',
                'ordering': ('-id',),
            },
        ),
    ]
