# Generated by Django 4.1 on 2024-10-21 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_name_group_unique_name_per_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='group.grade'),
        ),
    ]
