# Generated by Django 4.1 on 2024-10-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='年级名'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='group.grade', verbose_name='对应年级'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='班级名'),
        ),
    ]
