# Generated by Django 4.1 on 2024-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=1000)),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文件',
                'db_table': 'Files',
                'ordering': ('-id',),
            },
        ),
    ]
