# Generated by Django 4.1 on 2024-10-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 10, 7, 0, 40, 0, 708920))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 10, 7, 0, 40, 0, 708920))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
