# Generated by Django 4.1 on 2024-10-14 09:06

import activity.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_alter_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.TextField(max_length=10240, verbose_name='描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=50, verbose_name='地点')),
                ('capacity', models.PositiveIntegerField(verbose_name='最大报名容量')),
                ('type', models.IntegerField(choices=[(0, 'Sports'), (1, 'Art'), (2, 'Science'), (3, 'Other')], verbose_name='活动类别')),
                ('sign_info', models.JSONField(default=activity.models.default_sign_info, verbose_name='签到信息')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '活动',
                'db_table': 'activity',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Attender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_time', models.DateTimeField(default=datetime.datetime(2024, 10, 14, 9, 6, 5, 892827, tzinfo=datetime.timezone.utc), verbose_name='签到时间')),
                ('status', models.BooleanField(default=False, verbose_name='签到状态')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动签到记录',
                'db_table': 'activity_attendance',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(related_name='activity_attenders_set', through='activity.Attender', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AddConstraint(
            model_name='attender',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_attendance'),
        ),
    ]
