# Generated by Django 4.1 on 2024-10-14 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attender',
            name='sign_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 9, 7, 46, 207813, tzinfo=datetime.timezone.utc), verbose_name='签到时间'),
        ),
    ]
