# Generated by Django 4.1 on 2024-10-14 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_attender_sign_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attender',
            name='sign_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='签到时间'),
        ),
    ]
