# Generated by Django 4.1 on 2024-10-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_attender_sign_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='sign_info',
        ),
        migrations.AddField(
            model_name='activity',
            name='code_expired_time',
            field=models.DateTimeField(null=True, verbose_name='签到码过期时间'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sign_code',
            field=models.CharField(max_length=50, null=True, verbose_name='签到码'),
        ),
    ]
