# Generated by Django 4.1 on 2024-10-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_openid_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ('-id',), 'verbose_name': '注册信息'},
        ),
    ]
